---

- name: Include OS-specific vars
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"
  when:
    - ansible_facts['os_family'] is in ('Debian')

- name: Install nginx
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ nginx_packages }}"

# TODO - GET RID OF THIS
- name: Get nginx version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      nginx -v 2>&1 | cut -d'/' -f2
    executable: /bin/bash
  register: nginx_version
  changed_when: false # should never report changes

- name: Check if dhparam file exists
  ansible.builtin.stat:
    path: "{{ nginx_dhparam_path }}"
  register: dhparam_stat

# dpharams are only used when modern_ssl is set to 'intermediate', but will always be generated
- name: Generate dhparams
  community.crypto.openssl_dhparam:
    path: "{{ nginx_dhparam_path }}"
    size: "{{ nginx_dhparam_size }}"
  when: not dhparam_stat.stat.exists
  notify: Restart nginx

# Debian-based distros come with a default vhost that we don't want
- name: Delete default vhost files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
  when: ansible_facts['os_family'] == 'Debian'
  notify: Restart nginx

- name: Generate vhost configuration files
  ansible.builtin.template:
    src: vhost.j2
    dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
    mode: '0644'
    owner: root
    group: root
  # This will generate a single configuration file for each vhost
  with_items: "{{ nginx_proxies }}"
  notify: Restart nginx
  loop_control:
    label: "{{ item.name }}"

- name: Configure nginx service
  ansible.builtin.service:
    name: nginx
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"
